import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

// Handles the link generated by supabase.auth.admin.generateLink() and
// emailed via Resend in /api/auth/signup. Supabase's action_link points
// here (via the `redirectTo` we passed) with `token_hash` + `type` query
// params - verifyOtp() exchanges those for a real session and sets the
// session cookie via the SSR client below.
export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const token_hash = searchParams.get("token_hash");
  const type = searchParams.get("type");

  if (!token_hash || !type) {
    return NextResponse.redirect(new URL("/login?verify=invalid", request.url));
  }

  const cookieStore = await cookies();
  const supabaseAuth = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    {
      cookies: {
        getAll() { return cookieStore.getAll(); },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          );
        },
      },
    }
  );

  const { error } = await supabaseAuth.auth.verifyOtp({ token_hash, type });

  if (error) {
    console.error("[verify] verifyOtp failed:", error.message);
    const reason = error.message?.toLowerCase().includes("expired") ? "expired" : "error";
    return NextResponse.redirect(new URL(`/login?verify=${reason}`, request.url));
  }

  // Session cookie is now set - user is verified and signed in.
  return NextResponse.redirect(new URL("/?verify=success", request.url));
}