"use client";
import MarketingNav from "@/components/marketing/MarketingNav";
import MarketingFooter from "@/components/marketing/MarketingFooter";

const SECTIONS = [
  {
    id: "acceptance", title: "1. Acceptance of terms",
    body: ["By creating an account or using Helixon, you agree to these terms. If you're using Helixon on behalf of an agency, you're confirming you have authority to bind that agency to this agreement."],
  },
  {
    id: "the-service", title: "2. What Helixon does",
    body: ["Helixon analyses CVs against job descriptions and produces a match score, summary, and supporting evidence to help you make faster shortlisting decisions. It is a decision-support tool - Helixon does not make hiring decisions, and no output should be treated as the sole basis for rejecting or advancing a candidate."],
  },
  {
    id: "your-responsibilities", title: "3. Your responsibilities",
    body: [
      "You're responsible for having a lawful basis to process any CV you upload, for the accuracy of job descriptions and requirements you provide, and for how you use Helixon's output in real hiring decisions.",
      "You agree not to upload CVs you don't have a lawful basis to screen, not to use Helixon to discriminate against candidates on any protected characteristic, and not to attempt to reverse-engineer or abuse the scoring system.",
    ],
  },
  {
    id: "accuracy", title: "4. Accuracy & limitations",
    body: ["Match scores are generated by AI models and, like any automated assessment, can be wrong - particularly for scanned or poorly formatted CVs, unusual career histories, or ambiguous job descriptions. Always review the underlying evidence before acting on a score, and use your own judgement alongside it."],
  },
  {
    id: "plans-billing", title: "5. Plans & billing",
    body: ["Free accounts include a limited number of analyses. Paid plans (Solo, Team) are billed monthly and can be cancelled at any time from your account settings - you'll retain access until the end of the current billing period. We don't offer partial-month refunds, except where required by law."],
  },
  {
    id: "data", title: "6. Data handling",
    body: ["How we handle candidate and account data is covered in full in our Privacy Policy. In short: EU-hosted, never used to train models, deletable on request."],
  },
  {
    id: "liability", title: "7. Limitation of liability",
    body: ["Helixon is provided \"as is.\" To the maximum extent permitted by law, we're not liable for hiring decisions made using our output, indirect or consequential losses, or downtime beyond our reasonable control. Nothing in these terms limits liability for things that can't be limited by law, such as fraud or death or personal injury caused by negligence."],
  },
  {
    id: "changes", title: "8. Changes to these terms",
    body: ["We may update these terms as the product evolves. Material changes will be flagged in-app or by email ahead of taking effect. Continuing to use Helixon after a change takes effect means you accept the updated terms."],
  },
  {
    id: "contact", title: "9. Contact",
    body: ["Questions about these terms can be sent to hello@helixon.co.uk"],
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen" style={{ background: "var(--mist)" }}>
      <MarketingNav active="terms" />

      <section className="max-w-[900px] mx-auto px-6 pt-16 pb-14">
        <h1 className="text-4xl sm:text-5xl font-semibold tracking-tight leading-[1.08] mb-5" style={{ color: "var(--ink)", fontFamily: "var(--font-display)" }}>
          Terms of Service
        </h1>
        <p className="text-sm leading-relaxed max-w-xl" style={{ color: "var(--ink-soft)" }}>
          The rules for using Helixon, written to be read in one sitting.
        </p>
        <p className="text-[11px] mt-4" style={{ color: "var(--ink-faint)" }}>Last updated: August 2026</p>
      </section>

      <section className="max-w-[900px] mx-auto px-6 pb-24">
        <div className="rounded-[16px] p-8" style={{ background: "white", border: "1px solid var(--border)" }}>
          <div className="space-y-10">
            {SECTIONS.map((s) => (
              <div key={s.id} id={s.id}>
                <h2 className="text-base font-semibold tracking-tight mb-2.5" style={{ color: "var(--ink)", fontFamily: "var(--font-display)" }}>
                  {s.title}
                </h2>
                {s.body.map((p, i) => (
                  <p key={i} className="text-xs leading-relaxed mb-2.5" style={{ color: "var(--ink-soft)" }}>{p}</p>
                ))}
              </div>
            ))}
          </div>
        </div>
      </section>

      <MarketingFooter />
    </main>
  );
}